job('maven-web-file') {
	description("first maven job generated by dsl")
	scm {
		git("https://github.com/DhanunjayaO/sdl_project.git",main)
	}
	triggers {
		scm('* * * * *')
	}
	steps {
		maven('clean package')
	}
	publishers {
		archiveArtifacts '**/*.war'
	}
}
