job('maven-web-file') {
	description("first maven job generated by dsl")
	scm {
		git("https://github.com/DhanunjayaO/web-maven-file.git",master)
	}
	triggers {
		scm('* * * * *')
	}
	steps {
		maven('clean package')
	}
	publishers {
		archiveArtifacts '**/*.war'
	}
}
